// 00_angularjs/src/app/views/body/body.component.ts
import { Component, OnInit } from '@angular/core';
import { VentService } from '../../services/service.index';
import { BateauService } from '../../services/service.index';
import { Vent } from '../../models/vent.model';
import { Bateau } from '../../models/bateau.model';
import { interval } from 'rxjs';


@Component({
  selector: 'app-body',
  templateUrl: './body.component.html',
  styleUrls: ['./body.component.css'],
})
export class BodyComponent implements OnInit {

  vent: Vent = new Vent();
  bateau: Bateau = new Bateau();
  secondsCounter = interval(10000);


  constructor(
    public ventService: VentService,
    public bateauService: BateauService
  ) { }


  ngOnInit() {
    this.getData();
    this.secondsCounter.subscribe(n => {
      this.getData();
    });
  }



  getData() {

    const config = require('../../../../../config/config.json');

    if (config.database) {
      this.ventService.getVent()
        .subscribe((resp: any) => {

          if (resp.ok) {
            this.vent = resp.vent;

          }
        });
      this.bateauService.getBateau()
        .subscribe((resp: any) => {

          if (resp.ok) {
            this.bateau = resp.bateau;

          }
        });
    } else {
      this.vent = this.ventService.getVentJson();
      this.bateau = this.bateauService.getBateauJson();
    }

  }
}

<div class="row all-tableros">
    <div class="col-xs-12 col-sm-8 title">
        <span>Données de navigation</span>
    </div>
    <div class="w-100"></div>
    <div class="col-xs-12 col-md-8  tablero">
        <h2>Vitesse</h2>
        <p>{{ bateau.vitesseNoeud }} N</p>
        <app-gauge [childMessage]="bateau.vitesseKm"></app-gauge>
    </div>
    <div class="w-100"></div>
    <div class="col-xs-6 col-md-4 tablero">
        <h2>Route (COG)</h2>
        <p>{{ bateau.cap }} °</p>
    </div>
    <div class="col-xs-12 col-md-4 tablero">
        <h2>Compas</h2>
        <p>{{ bateau.compas }} N</p>
    </div>
    <div class="col-xs-12 col-md-8 tablero">
        <h2>Position</h2>
        <p>{{ bateau.position1 }}</p>
        <p>{{ bateau.position2 }}</p>
    </div>
    <div class="w-100"></div>
    <div class="col-xs-12 col-md-8 tablero">
        <h2>Direction (CAP) et Angle du vent</h2>
        <app-compas [data]='[bateau,vent]'></app-compas>
        <p id="vitesseVent">Vitesse actuelle du vent: {{ vent.vitesse }} km/h</p>
    </div>
    <div class="w-100"></div>
    <div class="col-xs-12 col-md-8 tablero">
        <h2>Historique</h2>
        <app-historique [bateau]='bateau'></app-historique>
    </div>
    <div class="w-100"></div>
</div>

// reactjs/src/Body.js
import React, { Component } from "react";
import Gauge from "./components/Gauge";
import Compas from "./components/Compas";
import Historique from "./components/Historique";

class Body extends Component {
  render() {
    const { vent, bateau } = this.props;

    return (
      <div className="container">
        <div className="row all-tableros">
          <div className="col-xs-12 col-sm-8 title">
            <span>Données de navigation</span>
          </div>
          <div className="w-100" />
          <div className="col-xs-12 col-md-8 tablero">
            <h2>Vitesse</h2>
            <p> {bateau.vitesseNoeud} N</p>
            <Gauge bateau={bateau} />
          </div>
          <div className="w-100" />
          <div className="col-xs-6 col-md-4 tablero">
            <h2>Route (COG)</h2>
            <p> {bateau.cap} °</p>
          </div>
          <div className="col-xs-12 col-md-4 tablero">
            <h2>Compas</h2>
            <p> {bateau.compas}N</p>
          </div>
          <div className="col-xs-12 col-md-8 tablero">
            <h2>Position</h2>
            <p> {bateau.position1}</p>
            <p> {bateau.position2}</p>
          </div>
          <div className="w-100" />
          <div className="col-xs-12 col-md-8 tablero">
            <h2>Direction (CAP) et Angle du vent</h2>
            <Compas bateau={bateau} vent={vent} />
            <p id="vitesseVent">
              Vitesse actuelle du vent: {vent.vitesse} km/h
            </p>
          </div>
          <div className="w-100" />
          <div className="col-xs-12 col-md-8 tablero">
            <h2>Historique</h2>
            <Historique bateau={bateau} />
          </div>
          <div className="w-100" />
        </div>
      </div>
    );
  }
}
export default Body;
