// angularjs/src/app/views/body/body.component.ts
import { Component, OnInit } from '@angular/core';
import { WindService } from '../../services/service.index';
import { BoatService } from '../../services/service.index';
import { Wind } from '../../models/wind.model';
import { Boat } from '../../models/boat.model';
import { interval } from 'rxjs';


@Component({
  selector: 'app-body',
  templateUrl: './body.component.html',
  styleUrls: ['./body.component.css'],
})
/**
 * html 'body' content
 */
export class BodyComponent implements OnInit {

  wind: Wind = new Wind();
  boat: Boat = new Boat();
  secondsCounter = interval(10000);


  constructor(
    public windService: WindService,
    public boatService: BoatService
  ) { }


  ngOnInit() {
    this.getData();
    this.secondsCounter.subscribe(n => {
      this.getData();
    });
  }



  getData() {
    /**
     * Call mock wind data from windService
     */
    this.windService.getWindData()
      .subscribe((resp: any) => {
        this.wind = resp;
        console.log(this.wind);

      });
    /**
     * Call mock boat data from boatService
     */
    this.boatService.getBoatData()
      .subscribe((resp: any) => {
        this.boat = resp;
      });

  }
}

<div class="row all-tableros">
    <div class="col-xs-12 col-sm-8 title">
        <span>Données de navigation</span>
    </div>
    <div class="w-100"></div>
    <div class="col-xs-12 col-md-8  tablero">
        <h2>Vitesse</h2>
        <p>{{ boat.vitesseNoeud }} N</p>
        <app-gauge [childMessage]="boat.vitesseKm"></app-gauge>
    </div>
    <div class="w-100"></div>
    <div class="col-xs-6 col-md-4 tablero">
        <h2>Route (COG)</h2>
        <p>{{ boat.cap }} °</p>
    </div>
    <div class="col-xs-12 col-md-4 tablero">
        <h2>Compas</h2>
        <p>{{ boat.compas }} N</p>
    </div>
    <div class="col-xs-12 col-md-8 tablero">
        <h2>Position</h2>
        <p>{{ boat.position1 }}</p>
        <p>{{ boat.position2 }}</p>
    </div>
    <div class="w-100"></div>
    <div class="col-xs-12 col-md-8 tablero">
        <h2>Direction (CAP) et Angle du wind</h2>
        <app-compas [data]='[boat,wind]'></app-compas>
        <p id="vitessewind">Vitesse actuelle du wind: {{ wind.vitesse }} km/h</p>
    </div>
    <div class="w-100"></div>
    <div class="col-xs-12 col-md-8 tablero">
        <h2>Historique</h2>
        <app-historique [boat]='boat'></app-historique>
    </div>
    <div class="w-100"></div>
</div>

// reactjs/src/Body.js
import React, { Component } from "react";
import Gauge from "./components/Gauge";
import Compas from "./components/Compas";
import Historique from "./components/Historique";


/**
 * html 'body' content
 */
class Body extends Component {
  render() {
    const { wind, boat } = this.props;

    return (
      <div className="container">
        <div className="row all-tableros">
          <div className="col-xs-12 col-sm-8 title">
            <span>Données de navigation</span>
          </div>
          <div className="w-100" />
          <div className="col-xs-12 col-md-8 tablero">
            <h2>Vitesse</h2>
            <p> {boat.vitesseNoeud} N</p>
            <Gauge boat={boat} />
          </div>
          <div className="w-100" />
          <div className="col-xs-6 col-md-4 tablero">
            <h2>Route (COG)</h2>
            <p> {boat.cap} °</p>
          </div>
          <div className="col-xs-12 col-md-4 tablero">
            <h2>Compas</h2>
            <p> {boat.compas}N</p>
          </div>
          <div className="col-xs-12 col-md-8 tablero">
            <h2>Position</h2>
            <p> {boat.position1}</p>
            <p> {boat.position2}</p>
          </div>
          <div className="w-100" />
          <div className="col-xs-12 col-md-8 tablero">
            <h2>Direction (CAP) et Angle du wind</h2>
            <Compas boat={boat} wind={wind} />
            <p id="vitessewind">
              Vitesse actuelle du wind: {wind.vitesse} km/h
            </p>
          </div>
          <div className="w-100" />
          <div className="col-xs-12 col-md-8 tablero">
            <h2>Historique</h2>
            <Historique boat={boat} />
          </div>
          <div className="w-100" />
        </div>
      </div>
    );
  }
}
export default Body;
