// angularjs/src/app/components/gauge/gauge.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-gauge',
  templateUrl: './gauge.component.html',
  styles: []
})
export class GaugeComponent implements OnInit {

  @Input() childMessage: any;
  constructor() { }

  ngOnInit() {
  }

}

<div class="contenedor">
    <div class="gauge-a"></div>
    <div class="gauge-b"></div>
    <div class="gauge-c" [style.transform]="'rotate(180deg)'"></div>
    <!-- <div class="gauge-c" [style.transform]="'rotate(' + ((childMessage)*2) + 'deg)'"></div> -->
    <div class="gauge-data">
        <h1 id="percent">{{ childMessage }} km/h</h1>
    </div>
</div>

// reactjs/src/components/Gauge.js
import React, { Component } from "react";

class Gauge extends Component {
  render() {
    const { boat } = this.props;
    const pStyle = {
      transform: "rotate(" + boat.vitesseKm + "deg)"
    };

    return (
      <div className="contenedor">
        <div className="gauge-a" />
        <div className="gauge-b" />

        <div className="gauge-c" style={pStyle} />
        <div className="gauge-data">
          <h1 id="percent">{boat.vitesseKm} km/h</h1>
        </div>
      </div>
    );
  }
}
export default Gauge;
